# Generated by Django 5.1 on 2025-05-08 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_policeprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimereport',
            name='user',
        ),
        migrations.RemoveField(
            model_name='crimestatus',
            name='report',
        ),
        migrations.DeleteModel(
            name='InvestigationNote',
        ),
        migrations.DeleteModel(
            name='CrimeReport',
        ),
        migrations.DeleteModel(
            name='CrimeStatus',
        ),
    ]
