# Generated by Django 5.1 on 2025-05-09 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_crimereport_user_remove_crimestatus_report_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('crime_location', models.CharField(max_length=255)),
                ('crime_date', models.DateField()),
                ('crime_time', models.TimeField()),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(max_length=10)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('solved', 'Solved')], default='waiting', max_length=20)),
                ('investigation_notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
